<div class="sidebar sidebar-main">
    <div class="blog__sidebar-main">
        <div class="blog__sidebar-search">
            <form method="get" action="http://blog.m2.mirasvit.com/blog/search/">
                <input type="search" name="q" placeholder="Search..." class="input-text required-entry" value="">
                <button class="action primary" title="Submit" type="submit">
                    <span><i class="fa fa-fw fa-search"></i></span>
                </button>
            </form>
        </div>
        <div class="block block-collapsible-nav blog__sidebar-category-tree">
            <div class="title block-collapsible-nav-title">
                <strong>Categories</strong>
            </div>
            <div class="block-collapsible-content content" id="block-collapsible-nav-blog">
                <ul class="nav items">
                    <li class="nav item level-1 ">
                        <a href="http://blog.m2.mirasvit.com/blog/fashion.html">Fashion</a>
                    </li>
                    <li class="nav item level-2 ">
                        <a href="http://blog.m2.mirasvit.com/blog/fashionable-quotes.html">Fashionable Quotes</a>
                    </li>
                    <li class="nav item level-2 ">
                        <a href="http://blog.m2.mirasvit.com/blog/fashion-tips.html">Fashion Tips</a>
                    </li>
                    <li class="nav item level-1 ">
                        <a href="http://blog.m2.mirasvit.com/blog/gadgets.html">Gadgets</a>
                    </li>
                    <li class="nav item level-1 ">
                        <a href="http://blog.m2.mirasvit.com/blog/home-stretch.html">Home Stretch</a>
                    </li>
                    <li class="nav item level-1 ">
                        <a href="http://blog.m2.mirasvit.com/blog/newsroom.html">Newsroom</a>
                    </li>
                    <li class="nav item level-2 ">
                        <a href="http://blog.m2.mirasvit.com/blog/corporate-news.html">Corporate News</a>
                    </li>
                    <li class="nav item level-2 ">
                        <a href="http://blog.m2.mirasvit.com/blog/case-study.html">Case Study</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="block blog__sidebar-recent">
            <div class="block-title">
                <strong>Recent Posts</strong>
            </div>
            <div class="block-content">
                <ol class="items">
                    <li class="item">
                        <a href="http://blog.m2.mirasvit.com/blog/meet-blu-mobile-phones.html">
                            <img data-pagespeed-high-res-src="http://blog.m2.mirasvit.com/media/blog/x47.jpg.pagespeed.ic.-OTmN0hlCL.webp" alt="Meet BLU Mobile Phones!" class="blog__post-featured-image" data-pagespeed-url-hash="710182920" src="http://blog.m2.mirasvit.com/media/blog/x47.jpg.pagespeed.ic.-OTmN0hlCL.webp" onload="pagespeed.switchToHighResAndMaybeBeacon(this);" onerror="this.onerror=null;pagespeed.switchToHighResAndMaybeBeacon(this);">
                        </a>
                        <a href="http://blog.m2.mirasvit.com/blog/meet-blu-mobile-phones.html">Meet BLU Mobile Phones!</a>
                    </li>
                    <li class="item">
                        <a href="http://blog.m2.mirasvit.com/blog/where-does-helpfulness-end.html">
                            <img data-pagespeed-high-res-src="http://blog.m2.mirasvit.com/media/blog/x21.jpg.pagespeed.ic.jQxUN4822m.webp" alt="Where Does Helpfulness End?" class="blog__post-featured-image" data-pagespeed-url-hash="3388582716" src="http://blog.m2.mirasvit.com/media/blog/x21.jpg.pagespeed.ic.jQxUN4822m.webp" onload="pagespeed.switchToHighResAndMaybeBeacon(this);" onerror="this.onerror=null;pagespeed.switchToHighResAndMaybeBeacon(this);">
                        </a>
                        <a href="http://blog.m2.mirasvit.com/blog/where-does-helpfulness-end.html">Where Does Helpfulness End?</a>
                    </li>
                    <li class="item">
                        <a href="http://blog.m2.mirasvit.com/blog/five-designers-you-will-love.html">
                            <img alt="Five Designers You Will Love!" class="blog__post-featured-image" data-pagespeed-url-hash="1230330880" src="http://blog.m2.mirasvit.com/media/blog/x18.jpg.pagespeed.ic.Cqn0_2-eg9.webp" onerror="this.onerror=null;pagespeed.lazyLoadImages.loadIfVisibleAndMaybeBeacon(this);">
                        </a>
                        <a href="http://blog.m2.mirasvit.com/blog/five-designers-you-will-love.html">Five Designers You Will Love!</a>
                    </li>
                    <li class="item">
                        <a href="http://blog.m2.mirasvit.com/blog/let-s-get-brewing.html">
                            <img alt="Let’s Get Brewing" class="blog__post-featured-image" data-pagespeed-url-hash="3977582558" src="http://blog.m2.mirasvit.com/media/blog/x23.jpg.pagespeed.ic.llKWNfshsK.webp" onerror="this.onerror=null;pagespeed.lazyLoadImages.loadIfVisibleAndMaybeBeacon(this);">
                        </a>
                        <a href="http://blog.m2.mirasvit.com/blog/let-s-get-brewing.html">Let’s Get Brewing</a>
                    </li>
                    <li class="item">
                        <a href="http://blog.m2.mirasvit.com/blog/most-famous-hill-stations-in-the-country.html">
                            <img alt="Most Famous Hill Stations In The Country" class="blog__post-featured-image" data-pagespeed-url-hash="3313366703" src="http://blog.m2.mirasvit.com/media/blog/x31.jpg.pagespeed.ic.Ap61I1_3Ta.webp" onerror="this.onerror=null;pagespeed.lazyLoadImages.loadIfVisibleAndMaybeBeacon(this);">
                        </a>
                        <a href="http://blog.m2.mirasvit.com/blog/most-famous-hill-stations-in-the-country.html">Most Famous Hill Stations In The Country</a>
                    </li>
                </ol>
            </div>
        </div>
    </div>
</div>
