<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \SM\Blog\Block\BlogList\Toolbar
 */

// phpcs:disable Magento2.Security.IncludeFile.FoundIncludeFile
// phpcs:disable PSR2.Methods.FunctionCallSignature.SpaceBeforeOpenBracket
?>
<?php if (count($block->getBlogCollection()) > 0) :?>
    <?php $widget = $this->helper(\Magento\Framework\Json\Helper\Data::class)->jsonDecode($block->getWidgetOptionsJson());
    $widgetOptions = $this->helper(\Magento\Framework\Json\Helper\Data::class)->jsonEncode($widget['blogListToolbarForm']);
    ?>
    <div class="toolbar blog-post-list__toolbar" data-mage-init='{"blogListToolbarForm":<?= /* @noEscape */ $widgetOptions ?>}'>

                <?php include ($block->getTemplateFile('toolbar/limiter.phtml')) ?>
    </div>
<?php endif ?>
