<?php
//@codingStandardsIgnoreFile

/** @var $block CategoryTree */

use SM\Blog\Block\Sidebar\CategoryTree;

?>
<style>
    .items li a{
        color: #0a0a0a;
    }
    .items li a:hover{
        color: #0a0a0a;
        text-decoration: none;
    }
    .items li:hover{
        background-color: #9ba8b5;
    }
</style>
<div class="block block-collapsible-nav blog__sidebar-category-tree">
    <div class="title block-collapsible-nav-title"
         data-mage-init='{"toggleAdvanced": {"toggleContainers": "#block-collapsible-nav-blog", "selectorsToggleClass": "active"}}'>
        <strong>Categories</strong>
    </div>
    <div class="block-collapsible-content content" id="block-collapsible-nav-blog">
        <ul class="nav items" >
            <?php echo $block->categoryRecusive(1); ?>
        </ul>
    </div>
</div>
